---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-volume-0
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/mysql-volume-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-volume-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/mysql-volume-1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
